---
title: "Pacific calculus decontam"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(decontam)
library(data.table)
library(janitor)
library(tidyverse)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```


Load metadata
```{r}

metadata_full <- fread("./05-Documentation.backup/eisenhoffer2020_ottoni2021_deepevo_mann2018w_metadata.tsv")  %>%
  rename(Library_ID = Run_accession) %>%
  full_join(., fread("./05-Documentation.backup/oceana_meta_decontam.tsv") %>%
              rename(Library_ID = SampleID) %>%
              filter(str_detect(Library_ID, "ARS"))) %>%
  mutate(Library_ID = ifelse(Study == "FellowsYates2021",Sample_alias,Library_ID)) %>%
  # indicate blanks
  mutate(Sample_or_Control = ifelse(str_detect(Sample_alias, "BLEX|EBC"),"control", "sample")) %>%
  mutate(Sample_or_Control = ifelse(is.na(Sample_or_Control), "control",Sample_or_Control))

metadata <- metadata_full %>%
  mutate(Sample_group = ifelse(is.na(Sample_group),"bone",Sample_group)) %>%
  filter(!str_detect(Sample_group, "primate|modern"))

# list the non-human primates and modern calculus to remove from the species table
nhp <- metadata_full %>%
  filter(str_detect(Sample_group, "primate|modern")) %>%
  select(Sample_alias) %>%
  pull()

```


```{r poorly_preserved}
cfdp_fail <- fread("05-Documentation.backup/cuperdec_malt_ei_ot_de_poor_samples.tsv") %>%
  rename(Library_ID = 1) 

```


```{r pca_plotting_functions}
# plotting PCA with colored dots
plot_pca <- function(df, pc1, pc2, metadata_group) {
    metadata_group_colors <- get(paste(metadata_group, "_colors", sep = ""))
    metadata_group_shapes <- get(paste(metadata_group, "_shapes", sep = ""))

    exp_var <- paste0(round(df$prop_expl_var$X * 100, 2), "%")
    df_X <- df$variates$X %>%
              as.data.frame() %>%
              rownames_to_column("Library_ID") %>%
              inner_join(metadata %>%
                           select(Library_ID, Sample_or_Control, Study), by = "Library_ID")
    
    metadata_group = df_X[[metadata_group]]
    
                       if (pc1 == 'PC1') {
                           pc1 <- df_X$PC1
                           exp_var_pc1 <- exp_var[1]
                           xaxis <- c("PC1")
                       }  else if (pc1 == 'PC2') {
                           pc1 <- df_X$PC2
                           exp_var_pc1 <- exp_var[2]
                           xaxis <- c("PC2")
                       } else if (pc1 == 'PC3') {
                           pc1 <- df_X$PC3
                           exp_var_pc1 <- exp_var[3]
                           xaxis <- c("PC3")
                       }

                       if (pc2 == 'PC1') {
                           pc2 <- df_X$PC1
                           exp_var_pc2 <- exp_var[1]
                           yaxis <- c("PC1")
                       }  else if (pc2 == 'PC2') {
                           pc2 <- df_X$PC2
                           exp_var_pc2 <- exp_var[2]
                           yaxis <- c("PC2")
                       } else if (pc2 == 'PC3') {
                           pc2 <- df_X$PC3
                           exp_var_pc2 <- exp_var[3]
                           yaxis <- c("PC3")
                       }

    pca_plot <- ggplot(df_X, aes(pc1, pc2, colour = metadata_group, shape = metadata_group)) +
                        geom_point(size = 4) +
                        scale_colour_manual(values = metadata_group_colors) +
                        scale_shape_manual(values = metadata_group_shapes) +
                        # stat_ellipse() +
                        xlab(paste(xaxis, " - ", exp_var_pc1)) +
                        ylab(paste(yaxis, " - ", exp_var_pc2)) +
                        theme_minimal(base_size = 10) +
                        theme(legend.position = "top") +
                        theme(legend.title = element_blank())

    return(pca_plot)
}

# this function plots the PCA with the sample names instead of points
plot_pca_names <- function(df, pc1, pc2, metadata_group) {
    metadata_group_colors <- get(paste(metadata_group, "_colors", sep = ""))

    exp_var <- paste0(round(df$prop_expl_var$X * 100, 2), "%")
    df_X <- df$variates$X %>%
              as.data.frame() %>%
              rownames_to_column("Library_ID") %>%
              inner_join(metadata %>%
                           select(Library_ID, Sample_or_Control,Study), by = "Library_ID")
    
    metadata_group = df_X[[metadata_group]]
    
                       if (pc1 == 'PC1') {
                           pc1 <- df_X$PC1
                           exp_var_pc1 <- exp_var[1]
                           xaxis <- c("PC1")
                       }  else if (pc1 == 'PC2') {
                           pc1 <- df_X$PC2
                           exp_var_pc1 <- exp_var[2]
                           xaxis <- c("PC2")
                       } else if (pc1 == 'PC3') {
                           pc1 <- df_X$PC3
                           exp_var_pc1 <- exp_var[3]
                           xaxis <- c("PC3")
                       }

                       if (pc2 == 'PC1') {
                           pc2 <- df_X$PC1
                           exp_var_pc2 <- exp_var[1]
                           yaxis <- c("PC1")
                       }  else if (pc2 == 'PC2') {
                           pc2 <- df_X$PC2
                           exp_var_pc2 <- exp_var[2]
                           yaxis <- c("PC2")
                       } else if (pc2 == 'PC3') {
                           pc2 <- df_X$PC3
                           exp_var_pc2 <- exp_var[3]
                           yaxis <- c("PC3")
                       }

    pca_plot_names <- ggplot(df_X, aes(pc1, pc2, colour = metadata_group)) +
                        geom_text(aes(label = Library_ID), size = 3) +
                        scale_colour_manual(values = metadata_group_colors) +
                        # stat_ellipse() +
                        xlab(paste(xaxis, " - ", exp_var_pc1)) +
                        ylab(paste(yaxis, " - ", exp_var_pc2)) +
                        theme_minimal(base_size = 10) +
                        theme(legend.position = "top") +
                        theme(legend.title = element_blank())

    return(pca_plot_names)
}

```


## Species
```{r load_species_tables}
# read in the species table
malt_raw <- fread("./05-Documentation.backup/eisenhoffer2020_malt_refseq_species.tsv") %>%
  rename(Species = 1) %>%
  full_join(., fread("./05-Documentation.backup/ottoni2021_malt_refseq_species.tsv") %>%
              rename(Species = 1)) %>%
  full_join(., fread("./05-Documentation.backup/sources_MALT_cRefSeq_JFY_species_summarized.txt") %>%
              rename(Species = 1) %>%
              select(matches("Species|ARS")), by = "Species") %>%
  full_join(., fread("./05-Documentation.backup/deep_evo_malt_refseq_comparison_species.tsv") %>%
              rename(Species = 1)) %>%
  full_join(., fread("./05-Documentation.backup/mann2018_world_malt_refseq_comparison_species.tsv") %>%
              rename(Species = 1)) %>%
  filter(Species != "Homo sapiens")

# clean the file names
colnames(malt_raw) <- gsub(".unmapped","", colnames(malt_raw))
colnames(malt_raw) <- gsub("MeganServer::", "", colnames(malt_raw)) 
colnames(malt_raw) <- gsub("_S0_L000_R1_000.fastq.merged.prefixed.hg1", "", colnames(malt_raw)) 
colnames(malt_raw) <- gsub("_S0_L001_R1_000.fastq.merged.prefixed.hg1", "", colnames(malt_raw)) 
colnames(malt_raw) <- gsub(".SG1.2_S0_L003_R1_001.fastq.combined.fq.prefixed.extrac.bam", "", colnames(malt_raw)) 

# replace NA with 0
malt_sp <- malt_raw %>% 
  replace(is.na(.), 0) %>%
  arrange(Species)

```


### Raw PCA
Before running decontam, let's plot the samples in a PCA to see if there are any that are clearly not good-quality
```{r raw_plot}

species_raw <- malt_sp %>%
  pivot_longer(!Species, names_to = "Library_ID", values_to = "Counts") %>%
  mutate(Counts = Counts + 1) %>%
  pivot_wider(names_from = "Species", values_from = "Counts") %>%
  column_to_rownames("Library_ID")

# prepare to run a PCA
# check the number of components to retain by tuning the PCA
tune.species_pca <- mixOmics::tune.pca(species_raw, logratio = 'CLR')
tune.species_pca

# perform a PCA to see how the data cluster
species_raw.pca <- mixOmics::pca(species_raw, ncomp = 3, logratio = 'CLR')
plot(species_raw.pca)

# define some colors
Sample_or_Control_colors = c("Blue", "Magenta")
Sample_or_Control_shapes = c(19,8)

Study_colors <- c("black","blue","turquoise", "red","orange")
Study_shapes <- c(19,17,15,9,8)

plot_pca(species_raw.pca, "PC1", "PC2", "Sample_or_Control")
plot_pca(species_raw.pca, "PC1", "PC2", "Study")
plot_pca_names(species_raw.pca,  "PC1", "PC2", "Sample_or_Control")

species_raw_pass <- malt_sp %>%
  pivot_longer(!Species, names_to = "Library_ID", values_to = "Counts") %>%
  mutate(Counts = Counts + 1) %>%
  pivot_wider(names_from = "Species", values_from = "Counts") %>%
  anti_join(., cfdp_fail) %>%
  column_to_rownames("Library_ID")

# prepare to run a PCA
# check the number of components to retain by tuning the PCA
tune.species_pca <- mixOmics::tune.pca(species_raw_pass, logratio = 'CLR')
tune.species_pca

# perform a PCA to see how the data cluster
species_raw_pass.pca <- mixOmics::pca(species_raw_pass, ncomp = 3, logratio = 'CLR')
plot(species_raw_pass.pca)

# define some colors
Sample_or_Control_colors = c("Blue", "Magenta")
Sample_or_Control_shapes = c(19,8)

plot_pca(species_raw_pass.pca, "PC1", "PC2", "Sample_or_Control")
plot_pca(species_raw_pass.pca, "PC1", "PC2", "Study")


```

```{r outliers_species}

species_raw_pass <- malt_sp %>%
  pivot_longer(!Species, names_to = "Library_ID", values_to = "Counts") %>%
  pivot_wider(names_from = "Species", values_from = "Counts") %>%
  anti_join(., cfdp_fail)

```

### Eisenhoffer2020

```{r eisenhoffer_data_prep}

# select only Otago samples and controls
# note that all poorly-preserved samples are removed from species_raw_pass although they're still in the eisenhoffer list
eisenhoffer_df <- species_raw_pass %>%
  filter(str_detect(Library_ID, "SRR|ARS")) %>%
  pivot_longer(!Library_ID, names_to = "Species", values_to = "Counts") %>%
  pivot_wider(names_from = "Library_ID", values_from = "Counts") %>%
  adorn_totals(where = "col") %>%
  filter(Total > 0) %>%
  select(-Total) %>%
  pivot_longer(!Species, names_to = "Library_ID", values_to = "Counts") %>%
  pivot_wider(names_from = "Species", values_from = "Counts")

# make a matrix for decontam
eisenhoffer_matrix <- data.matrix(eisenhoffer_df[2:ncol(eisenhoffer_df)])
rownames(eisenhoffer_matrix) <- eisenhoffer_df$Library_ID

# make a metadata dataframe with the same samples 
eisenhoffer_metadata <- eisenhoffer_df %>%
  select(Library_ID) %>%
  left_join(., metadata, by = "Library_ID")

```

```{r eisenhoffer_prevalence}
# Assign sample-type status to identify control samples
eisenhoffer_metadata$is.control <- eisenhoffer_metadata$Sample_or_Control=="control"

#Try changing the probability threshold cut-off to see how many more or less are ID'd as contaminants
contam.prev.eisenhoffer <- isContaminant(eisenhoffer_matrix, method="prevalence", 
                                 neg=eisenhoffer_metadata$is.control, 
                                 threshold = 0.9)

# Check number of contaminants
table(contam.prev.eisenhoffer$contaminant)

# List of contaminants
contam.prev.eisenhoffer <- contam.prev.eisenhoffer %>%
  as_tibble() %>%
  mutate(Species = row.names(contam.prev.eisenhoffer)) %>%
  select(Species, everything())

contam.prev.eisenhoffer_list <- contam.prev.eisenhoffer %>%
  filter(contaminant == "TRUE") %>%
  arrange(Species)

# Look at the histogram - does the probability threshold need to be changed?
ggplot(contam.prev.eisenhoffer, aes(x=p)) +
  geom_histogram(bins=100) +
  scale_y_log10() +
  ggtitle('Prevalence - Eisenhoffer2020')

```


```{r contaminants, eval = F}
contaminant_eisenhoffer_sp <- contam.prev.eisenhoffer_list %>% select(Species)
# fwrite(contaminant_eisenhoffer_sp, file = "./05-Documentation.backup/contaminant_eisenhoffer_sp.tsv", sep="\t", quote=F)
fwrite(contaminant_eisenhoffer_sp, file = "../strep_clades/00-documentation/contaminant_eisenhoffer_sp.tsv", sep="\t", quote=F)

```


### Ottoni2021

```{r ottoni_data_prep}
# select only Otago samples and controls
# note that all poorly-preserved samples are removed from species_raw_pass although they're still in the ottoni list
ottoni_df <- species_raw_pass %>%
  filter(str_detect(Library_ID, "ERR|ARS")) %>%
  pivot_longer(!Library_ID, names_to = "Species", values_to = "Counts") %>%
  pivot_wider(names_from = "Library_ID", values_from = "Counts") %>%
  adorn_totals(where = "col") %>%
  filter(Total > 0) %>%
  select(-Total) %>%
  pivot_longer(!Species, names_to = "Library_ID", values_to = "Counts") %>%
  pivot_wider(names_from = "Species", values_from = "Counts")

# make a matrix for decontam
ottoni_matrix <- data.matrix(ottoni_df[2:ncol(ottoni_df)])
rownames(ottoni_matrix) <- ottoni_df$Library_ID

# make a metadata dataframe with the same samples 
ottoni_metadata <- ottoni_df %>%
  select(Library_ID) %>%
  left_join(., metadata, by = "Library_ID")

```

```{r ottoni_prevalence}
# Assign sample-type status to identify control samples
ottoni_metadata$is.control <- ottoni_metadata$Sample_or_Control=="control"

#Try changing the probability threshold cut-off to see how many more or less are ID'd as contaminants
contam.prev.ottoni <- isContaminant(ottoni_matrix, method="prevalence", 
                                 neg=ottoni_metadata$is.control, 
                                 threshold = 0.75) 

# Check number of contaminants
table(contam.prev.ottoni$contaminant)

# List of contaminants
contam.prev.ottoni <- contam.prev.ottoni %>%
  as_tibble() %>%
  mutate(Species = row.names(contam.prev.ottoni)) %>%
  select(Species, everything())

contam.prev.ottoni_list <- contam.prev.ottoni %>%
  filter(contaminant == "TRUE") %>%
  arrange(Species)

# Look at the histogram - does the probability threshold need to be changed?
ggplot(contam.prev.ottoni, aes(x=p)) +
  geom_histogram(bins=100) +
  scale_y_log10() +
  ggtitle('Prevalence - Ottoni2021')

```

```{r contaminants, eval = F}
contaminant_ottoni_sp <- contam.prev.ottoni_list %>% select(Species)
# fwrite(contaminant_ottoni_sp, file = "./05-Documentation.backup/contaminant_ottoni_sp.tsv", sep="\t", quote=F)
fwrite(contaminant_ottoni_sp, file = "../strep_clades/00-documentation/contaminant_ottoni_sp.tsv", sep="\t", quote=F)

```

### DeepEvo

```{r deepevo_data_prep}
# select only DeepEvo samples and controls
deepevo_df <- species_raw_pass %>%
  filter(!str_detect(Library_ID, "ERR|SRR")) %>%
  select(-matches(nhp)) %>%
  pivot_longer(!Library_ID, names_to = "Species", values_to = "Counts") %>%
  pivot_wider(names_from = "Library_ID", values_from = "Counts") %>%
  adorn_totals(where = "col") %>%
  filter(Total > 0) %>%
  select(-Total) %>%
  pivot_longer(!Species, names_to = "Library_ID", values_to = "Counts") %>%
  pivot_wider(names_from = "Species", values_from = "Counts")

# make a matrix for decontam
deepevo_matrix <- data.matrix(deepevo_df[2:ncol(deepevo_df)])
rownames(deepevo_matrix) <- deepevo_df$Library_ID

# make a metadata dataframe with the same samples 
deepevo_metadata <- deepevo_df %>%
  select(Library_ID) %>%
  left_join(., metadata, by = "Library_ID")

```

```{r deepevo_prevalence}
# Assign sample-type status to identify control samples
deepevo_metadata$is.control <- deepevo_metadata$Sample_or_Control=="control"

#Try changing the probability threshold cut-off to see how many more or less are ID'd as contaminants
contam.prev.deepevo <- isContaminant(deepevo_matrix, method="prevalence", 
                                 neg=deepevo_metadata$is.control, 
                                 threshold = 0.51) 

# Check number of contaminants
table(contam.prev.deepevo$contaminant)

# List of contaminants
contam.prev.deepevo <- contam.prev.deepevo %>%
  as_tibble() %>%
  mutate(Species = row.names(contam.prev.deepevo)) %>%
  select(Species, everything())

contam.prev.deepevo_list <- contam.prev.deepevo %>%
  filter(contaminant == "TRUE") %>%
  arrange(Species)

# Look at the histogram - does the probability threshold need to be changed?
ggplot(contam.prev.deepevo, aes(x=p)) +
  geom_histogram(bins=100) +
  scale_y_log10() +
  ggtitle('Prevalence - deepevo2021')

```

```{r contaminants, eval = F}
contaminant_deepevo_sp <- contam.prev.deepevo_list %>% select(Species)
# fwrite(contaminant_deepevo_sp, file = "./05-Documentation.backup/contaminant_deepevo_sp.tsv", sep="\t", quote=F)
fwrite(contaminant_deepevo_sp, file = "../strep_clades/00-documentation/contaminant_deepevo_sp.tsv", sep="\t", quote=F)

```


## Mann2018 world
```{r mann2018world_data_prep}
# select only Mann 2018 world samples and controls
mw2018_df <- species_raw_pass %>%
  filter(!str_detect(Library_ID, "ERR|SRR")) %>%
  select(-matches(nhp)) %>%
  pivot_longer(!Library_ID, names_to = "Species", values_to = "Counts") %>%
  pivot_wider(names_from = "Library_ID", values_from = "Counts") %>%
  adorn_totals(where = "col") %>%
  filter(Total > 0) %>%
  select(-Total) %>%
  pivot_longer(!Species, names_to = "Library_ID", values_to = "Counts") %>%
  pivot_wider(names_from = "Species", values_from = "Counts")

# make a matrix for decontam
mw2018_matrix <- data.matrix(mw2018_df[2:ncol(mw2018_df)])
rownames(mw2018_matrix) <- mw2018_df$Library_ID

# make a metadata dataframe with the same samples 
mw2018_metadata <- mw2018_df %>%
  select(Library_ID) %>%
  left_join(., metadata, by = "Library_ID")

```

```{r mann2018world_prevalence}
# Assign sample-type status to identify control samples
mw2018_metadata$is.control <- mw2018_metadata$Sample_or_Control=="control"

#Try changing the probability threshold cut-off to see how many more or less are ID'd as contaminants
contam.prev.mw2018 <- isContaminant(mw2018_matrix, method="prevalence", 
                                 neg=mw2018_metadata$is.control, 
                                 threshold = 0.5) 

# Check number of contaminants
table(contam.prev.mw2018$contaminant)

# List of contaminants
contam.prev.mw2018 <- contam.prev.mw2018 %>%
  as_tibble() %>%
  mutate(Species = row.names(contam.prev.mw2018)) %>%
  select(Species, everything())

contam.prev.mw2018_list <- contam.prev.mw2018 %>%
  filter(contaminant == "TRUE") %>%
  arrange(Species)

# Look at the histogram - does the probability threshold need to be changed?
ggplot(contam.prev.mw2018, aes(x=p)) +
  geom_histogram(bins=100) +
  scale_y_log10() +
  ggtitle('Prevalence - mw20182021')

```

```{r contaminants, eval = F}
contaminant_mw2018_sp <- contam.prev.mw2018_list %>% select(Species)
# fwrite(contaminant_mw2018_sp, file = "./05-Documentation.backup/contaminant_mw2018_sp.tsv", sep="\t", quote=F)
fwrite(contaminant_mw2018_sp, file = "./05-Documentation.backup/contaminant_mw2018_sp.tsv", sep="\t", quote=F)

```












